### ISSUE TITLE
Bootstrap link has changed, making the directory empty

### ISSUE THREAD

**Issue by greyshi** [blanchardjeremy/hyde-bootstrap#6]
If this ever gets updated to use Bootstrap 3 this would be solved in the process

**Comment by willpatera** [comment]
This should be resolved by latest merge that @auzigog has made.  I don't have a ton of experience with git submodules, so I had to tinker around with my local repo to update the bootstrap link/submodule.  Let's see if this solves the problem.

**Comment by blanchardjeremy** [comment]
@willpatera Let me know if it works for you so I can close this ticket. Thanks!

**Comment by willpatera** [comment]
The bootstrap submodule is now for me.  @Aghoreyshi could you check to see if this solves the original problem?  I think there is still some work to do on the update-bootstrap-libs.sh script -- however that could be considered a separate issue.  More testing needed, I think, before I would say "resolved."

**Comment by blanchardjeremy** [comment]
Resolved with recent updates.
